// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: workforce/leave/v1/leave_entitlement_service.proto

package leavev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetLeaveEntitlementRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetLeaveEntitlementRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetLeaveEntitlementRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetLeaveEntitlementRequestMultiError, or nil if none found.
func (m *GetLeaveEntitlementRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetLeaveEntitlementRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetLeaveEntitlementRequestMultiError(errors)
	}

	return nil
}

// GetLeaveEntitlementRequestMultiError is an error wrapping multiple
// validation errors returned by GetLeaveEntitlementRequest.ValidateAll() if
// the designated constraints aren't met.
type GetLeaveEntitlementRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetLeaveEntitlementRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetLeaveEntitlementRequestMultiError) AllErrors() []error { return m }

// GetLeaveEntitlementRequestValidationError is the validation error returned
// by GetLeaveEntitlementRequest.Validate if the designated constraints aren't met.
type GetLeaveEntitlementRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetLeaveEntitlementRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetLeaveEntitlementRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetLeaveEntitlementRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetLeaveEntitlementRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetLeaveEntitlementRequestValidationError) ErrorName() string {
	return "GetLeaveEntitlementRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetLeaveEntitlementRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetLeaveEntitlementRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetLeaveEntitlementRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetLeaveEntitlementRequestValidationError{}

// Validate checks the field values on GetLeaveEntitlementResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetLeaveEntitlementResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetLeaveEntitlementResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetLeaveEntitlementResponseMultiError, or nil if none found.
func (m *GetLeaveEntitlementResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetLeaveEntitlementResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetLeaveEntitlement()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetLeaveEntitlementResponseValidationError{
					field:  "LeaveEntitlement",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetLeaveEntitlementResponseValidationError{
					field:  "LeaveEntitlement",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLeaveEntitlement()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetLeaveEntitlementResponseValidationError{
				field:  "LeaveEntitlement",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetLeaveEntitlementResponseMultiError(errors)
	}

	return nil
}

// GetLeaveEntitlementResponseMultiError is an error wrapping multiple
// validation errors returned by GetLeaveEntitlementResponse.ValidateAll() if
// the designated constraints aren't met.
type GetLeaveEntitlementResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetLeaveEntitlementResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetLeaveEntitlementResponseMultiError) AllErrors() []error { return m }

// GetLeaveEntitlementResponseValidationError is the validation error returned
// by GetLeaveEntitlementResponse.Validate if the designated constraints
// aren't met.
type GetLeaveEntitlementResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetLeaveEntitlementResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetLeaveEntitlementResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetLeaveEntitlementResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetLeaveEntitlementResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetLeaveEntitlementResponseValidationError) ErrorName() string {
	return "GetLeaveEntitlementResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetLeaveEntitlementResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetLeaveEntitlementResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetLeaveEntitlementResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetLeaveEntitlementResponseValidationError{}
